"""created_at col - generate time in DB and use UTC and add new updated_at col

Revision ID: 0964e5a49025
Revises: bdc2fc2105d2
Create Date: 2026-05-11 18:35:47.087692

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0964e5a49025"
down_revision = "bdc2fc2105d2"
branch_labels = None
depends_on = None


# --------------------- Manually added helper functions ---------------------

# Name for the trigger function
TRIGGER_FUNC_NAME = "auto_update_timestamp"


def create_trigger_function(column):
    """Creates a trigger function for a specific column."""
    function_name = f"{TRIGGER_FUNC_NAME}_{column}"
    return sa.DDL(
        f"""
        CREATE OR REPLACE FUNCTION {function_name}()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.{column} = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )


def drop_trigger_function(column):
    """Drops a trigger function for a specific column."""
    function_name = f"{TRIGGER_FUNC_NAME}_{column}"
    return sa.DDL(f"DROP FUNCTION IF EXISTS {function_name}();")


def create_update_timestamp_trigger(target, column="updated_at"):
    """Creates a trigger for a table to auto-update a timestamp column."""
    trigger_name = f"trigger_{target}_auto_update"
    function_name = f"{TRIGGER_FUNC_NAME}_{column}"
    return sa.DDL(
        f"""
        CREATE TRIGGER {trigger_name}
        BEFORE UPDATE ON "{target}"
        FOR EACH ROW
        EXECUTE FUNCTION {function_name}();
        """
    )


def drop_trigger(target):
    """Drops a trigger for a table."""
    trigger_name = f"trigger_{target}_auto_update"
    return sa.DDL(f'DROP TRIGGER IF EXISTS {trigger_name} ON "{target}";')


# ----------------- end of manually added helper functions ------------------


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(create_trigger_function("updated_at"))  # line added manually
    op.execute(create_trigger_function("updated_on"))  # line added manually
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            server_default=sa.text("now()"),  # line added manually
            existing_nullable=False,
        )
    op.execute("UPDATE category SET updated_at = created_at")  # line added manually
    op.execute(create_update_timestamp_trigger("category"))  # line added manually

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            server_default=sa.text("now()"),  # line added manually
            existing_nullable=False,
        )
    op.execute("UPDATE product SET updated_at = created_at")  # line added manually
    op.execute(create_update_timestamp_trigger("product"))  # line added manually

    with op.batch_alter_table("subcategory", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            server_default=sa.text("now()"),  # line added manually
            existing_nullable=False,
        )
    op.execute("UPDATE subcategory SET updated_at = created_at")  # line added manually
    op.execute(create_update_timestamp_trigger("subcategory"))  # line added manually

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_on",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.alter_column(
            "created_on",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            server_default=sa.text("now()"),  # line added manually
            existing_nullable=False,
        )
    op.execute('UPDATE "user" SET updated_on = created_on')  # line added manually
    op.execute(
        create_update_timestamp_trigger("user", column="updated_on")
    )  # line added manually

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(drop_trigger("user"))  # line added manually
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "created_on",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_column("updated_on")

    op.execute(drop_trigger("subcategory"))  # line added manually
    with op.batch_alter_table("subcategory", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_column("updated_at")

    op.execute(drop_trigger("product"))  # line added manually
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_column("updated_at")

    op.execute(drop_trigger("category"))  # line added manually
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_column("updated_at")

    op.execute(drop_trigger_function("updated_at"))  # line added manually
    op.execute(drop_trigger_function("updated_on"))  # line added manually

    # ### end Alembic commands ###
