"""use citext for case-insensitive unique names

Revision ID: 16620fd3081a
Revises: 0964e5a49025
Create Date: 2026-05-14 11:30:48.634535

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "16620fd3081a"
down_revision = "0964e5a49025"
branch_labels = None
depends_on = None


def upgrade():
    # --- manually added: enable citext extension ---
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # --- manually added: resolve case-conflicts before citext migration ---
    for table in ("category", "subcategory", "product"):
        op.execute(f"""
            DELETE FROM {table} a
            USING {table} b
            WHERE a.id > b.id
                AND LOWER(a.name) = LOWER(b.name)
        """)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=200),
            type_=postgresql.CITEXT(length=200),
            existing_nullable=False,
        )

    with op.batch_alter_table("subcategory", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=200),
            type_=postgresql.CITEXT(length=200),
            existing_nullable=False,
        )

    # ### end Alembic commands ###

    # --- code block manually added: product has a computed column depending on name,
    # so batch_alter_table cannot alter the column type. Drop and recreate. ---
    op.drop_index(op.f("product_search_vector_idx"), table_name="product")
    op.drop_column("product", "search_vector")
    op.alter_column(
        "product",
        "name",
        existing_type=sa.VARCHAR(length=200),
        type_=postgresql.CITEXT(length=200),
        existing_nullable=False,
        postgresql_using="name::citext",
    )
    op.add_column(
        "product",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(name, '')), 'A') || "
                "setweight(to_tsvector('english', coalesce(description, '')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("product_search_vector_idx"),
        "product",
        ["search_vector"],
        postgresql_using="gin",
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subcategory", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=postgresql.CITEXT(length=200),
            type_=sa.VARCHAR(length=200),
            existing_nullable=False,
        )

    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=postgresql.CITEXT(length=200),
            type_=sa.VARCHAR(length=200),
            existing_nullable=False,
        )

    # ### end Alembic commands ###

    # --- code block manually added: product has a computed column depending on name ---
    op.drop_index(op.f("product_search_vector_idx"), table_name="product")
    op.drop_column("product", "search_vector")
    op.alter_column(
        "product",
        "name",
        existing_type=postgresql.CITEXT(length=200),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
        postgresql_using="name::varchar",
    )
    op.add_column(
        "product",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(name, '')), 'A') || "
                "setweight(to_tsvector('english', coalesce(description, '')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("product_search_vector_idx"),
        "product",
        ["search_vector"],
        postgresql_using="gin",
    )
    op.execute("DROP EXTENSION IF EXISTS citext")  # line added manually
