"""Add postgres full text search for products

Revision ID: bdc2fc2105d2
Revises: 911b11318ef1
Create Date: 2026-05-10 07:39:35.452565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdc2fc2105d2'
down_revision = '911b11318ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(name, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B')", persisted=True), nullable=False))
        batch_op.create_index(batch_op.f('product_search_vector_idx'), ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('product_search_vector_idx'), postgresql_using='gin')
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
