"""Initial migration

Revision ID: c2ba8ccc9a6f
Revises: 
Create Date: 2025-01-17 17:06:38.552656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ba8ccc9a6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey')),
    sa.UniqueConstraint('name', name=op.f('category_name_key'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('product_pkey')),
    sa.UniqueConstraint('name', name=op.f('product_name_key'))
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('subcategory_pkey')),
    sa.UniqueConstraint('name', name=op.f('subcategory_name_key'))
    )
    op.create_table('category_subcategory',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('category_subcategory_category_id_fkey')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], name=op.f('category_subcategory_subcategory_id_fkey'))
    )
    op.create_table('subcategory_product',
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('subcategory_product_product_id_fkey')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], name=op.f('subcategory_product_subcategory_id_fkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategory_product')
    op.drop_table('category_subcategory')
    op.drop_table('subcategory')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
