"""Add indexes, primary keys on join tables. ondelete cascade on primary keys and so passive_deletes=True in relationships.

Revision ID: ec7ff666caa2
Revises: c2ba8ccc9a6f
Create Date: 2025-01-21 01:51:04.078090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec7ff666caa2'
down_revision = 'c2ba8ccc9a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('category_subcategory', schema=None) as batch_op:
        batch_op.create_index('category_subcategory_subcategory_id_idx', ['subcategory_id', 'category_id'], unique=False)
        batch_op.drop_constraint('category_subcategory_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('category_subcategory_subcategory_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('category_subcategory_category_id_fkey'), 'category', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('category_subcategory_subcategory_id_fkey'), 'subcategory', ['subcategory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

        batch_op.create_primary_key('category_subcategory_pkey', ['category_id', 'subcategory_id']) # Added manually

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('subcategory_product', schema=None) as batch_op:
        batch_op.create_index('subcategory_product_product_id_idx', ['product_id', 'subcategory_id'], unique=False)
        batch_op.drop_constraint('subcategory_product_subcategory_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('subcategory_product_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subcategory_product_subcategory_id_fkey'), 'subcategory', ['subcategory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('subcategory_product_product_id_fkey'), 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

        batch_op.create_primary_key('subcategory_product_pkey', ['subcategory_id', 'product_id']) # Added manually

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subcategory_product_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('subcategory_product_subcategory_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('subcategory_product_product_id_fkey', 'product', ['product_id'], ['id'])
        batch_op.create_foreign_key('subcategory_product_subcategory_id_fkey', 'subcategory', ['subcategory_id'], ['id'])
        batch_op.drop_index('subcategory_product_product_id_idx')

        batch_op.drop_constraint('subcategory_product_pkey', type_='primary') # added manually

    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('category_subcategory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('category_subcategory_subcategory_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('category_subcategory_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('category_subcategory_subcategory_id_fkey', 'subcategory', ['subcategory_id'], ['id'])
        batch_op.create_foreign_key('category_subcategory_category_id_fkey', 'category', ['category_id'], ['id'])
        batch_op.drop_index('category_subcategory_subcategory_id_idx')

        batch_op.drop_constraint('category_subcategory_pkey', type_='primary') # added manually

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
