name: Tests

on:
    workflow_call:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              id: cp312
              with:
                python-version-file: ".python-version"
                cache: "pip"
                cache-dependency-path: "requirements-test.txt"

            # for testing
            - name: Check cache hit
              run: echo "${{ steps.cp312.outputs.cache-hit }}" # true if cache-hit occurred on the primary key

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-test.txt

            - name: Run tests
              run: |
                  pytest --disable-warnings -q -rA
